import "@css/animate.css";
import "@css/bootstrap.min.css";
import "@css/font-awesome.css";
import "@css/magnific-popup.css";
import "@css/main.css";
import "@css/meanmenu.css";
import "@css/nice-select.css";
import "@css/swiper-bundle.min.css";
import "./../globals.css";
import Preloader from "@/layouts/Preloader";
import { ThemeProvider } from "@/components/ThemeProvider";
import LanguageProvider from "@/i18n/LanguageProvider";
import { getMessages } from 'next-intl/server';
import CookieConsentComponent from "@/components/CookieConsent";

export const metadata = {
  title: "Next - Multi-Purpose React NextJS Template",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.1.0/dist/cookieconsent.css" />

      </head>
      <body suppressHydrationWarning>
        <LanguageProvider messages={messages} locale={locale}>
          <ThemeProvider attribute="class" defaultTheme="light">
            <CookieConsentComponent />

            {/* <Preloader /> */}
            {children}
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
